services:

  archive-warrior:

    cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_ADMIN"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"

    container_name: "archive-warrior"

    entrypoint:
      - "python"
      - "start.py"

    environment:
      - "PYTHON_VERSION=3.9.5"
      - "PYTHON_PIP_VERSION=21.1.1"
      - "PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/1954f15b3f102ace496a34a013ea76b061535bd2/public/get-pip.py"
      - "PYTHON_GET_PIP_SHA256=f499d76e0149a673fb8246d88e116db589afbd291739bd84f2cd9a7bca7b6993"
      - "WARRIOR_ID=SneakyPie"
      - "CONCURRENT_ITEMS=3"
      - "SELECTED_PROJECT=reddit"
      - "PATH=/home/warrior/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "LANG=C.UTF-8"
      - "GPG_KEY=E3FF2839C048B25C084DEBE9B26995E310250568"
      - "PYTHON_SETUPTOOLS_VERSION=58.1.0"
      - "LC_ALL=C"

    hostname: "081e30b01804"

    image: "atdr.meo.ws/archiveteam/warrior-dockerfile:latest"

    ipc: "private"

    labels:
      org.opencontainers.image.created: "2021-06-08T14:03:49Z"
      org.opencontainers.image.revision: "54a26b7546c21191fbbf0b45f4984ea8a1567287"
      org.opencontainers.image.source: "https://github.com/ArchiveTeam/warrior-dockerfile.git"
      org.opencontainers.image.url: "https://github.com/ArchiveTeam/warrior-dockerfile"
      version: "20230408.01"
      wget-at.version: "1.21.3-at.20230208.01"

    logging:
      driver: "journald"
      options: {}

    mac_address: "02:42:ac:11:00:0f"

    network_mode: "bridge"

    ports:
      - "8001:8001/tcp"

    restart: "always"

    user: "warrior"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

    working_dir: "/home/warrior"