services:

  archive-warrior:

    container_name: "archive-warrior"

    entrypoint:
      - "python"
      - "start.py"

    environment:
      - "PYTHON_VERSION=3.9.5"
      - "PYTHON_PIP_VERSION=21.1.1"
      - "PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/1954f15b3f102ace496a34a013ea76b061535bd2/public/get-pip.py"
      - "PYTHON_GET_PIP_SHA256=f499d76e0149a673fb8246d88e116db589afbd291739bd84f2cd9a7bca7b6993"
      - "WARRIOR_ID=SneakyPie"
      - "CONCURRENT_ITEMS=3"
      - "SELECTED_PROJECT=reddit"
      - "PATH=/home/warrior/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "LANG=C.UTF-8"
      - "GPG_KEY=E3FF2839C048B25C084DEBE9B26995E310250568"
      - "PYTHON_SETUPTOOLS_VERSION=58.1.0"
      - "LC_ALL=C"

    hostname: "archive-warrior"

    image: "atdr.meo.ws/archiveteam/warrior-dockerfile:latest"

    logging:
      driver: "journald"
      options: {}

    network_mode: "bridge"

    ports:
      - "8001:8001/tcp"

    restart: "unless-stopped"

    user: "1000"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

    working_dir: "/home/warrior"
