services:

    duplicati:
  
      cap_drop:
        - "AUDIT_CONTROL"
        - "BLOCK_SUSPEND"
        - "DAC_READ_SEARCH"
        - "IPC_LOCK"
        - "IPC_OWNER"
        - "LEASE"
        - "LINUX_IMMUTABLE"
        - "MAC_ADMIN"
        - "MAC_OVERRIDE"
        - "NET_ADMIN"
        - "NET_BROADCAST"
        - "SYSLOG"
        - "SYS_ADMIN"
        - "SYS_BOOT"
        - "SYS_MODULE"
        - "SYS_NICE"
        - "SYS_PACCT"
        - "SYS_PTRACE"
        - "SYS_RAWIO"
        - "SYS_RESOURCE"
        - "SYS_TIME"
        - "SYS_TTY_CONFIG"
        - "WAKE_ALARM"
  
      container_name: "duplicati"
  
      entrypoint:
        - "/init"
  
      environment:
        - "PUID=0"
        - "PGID=0"
        - "TZ=America/New_York"
        - "PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        - "HOME=/config"
        - "LANGUAGE=en_US.UTF-8"
        - "LANG=en_US.UTF-8"
        - "TERM=xterm"
        - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
        - "S6_VERBOSITY=1"
        - "S6_STAGE2_HOOK=/docker-mods"
        - "VIRTUAL_ENV=/lsiopy"
        - "LSIO_FIRST_PARTY=true"
        - "DEBIAN_FRONTEND=noninteractive"
  
      hostname: "9ad36532006f"
  
      image: "docker.io/linuxserver/duplicati:latest"
  
      ipc: "private"
  
      labels:
        build_version: "Linuxserver.io version:- v2.0.6.3-2.0.6.3_beta_2021-06-17-ls167\
          \ Build-date:- 2023-05-20T03:51:31+00:00"
        maintainer: "aptalca"
        org.opencontainers.image.authors: "linuxserver.io"
        org.opencontainers.image.created: "2023-05-20T03:51:31+00:00"
        org.opencontainers.image.description: "[Duplicati](https://www.duplicati.com/)\
          \ works with standard protocols like FTP, SSH, WebDAV as well as popular services\
          \ like Microsoft OneDrive, Amazon Cloud Drive & S3, Google Drive, box.com,\
          \ Mega, hubiC and many others."
        org.opencontainers.image.documentation: "https://docs.linuxserver.io/images/docker-duplicati"
        org.opencontainers.image.licenses: "GPL-3.0-only"
        org.opencontainers.image.ref.name: "34fe8df98ec78de5e63eca32ce0ab2c5f3ed53e9"
        org.opencontainers.image.revision: "34fe8df98ec78de5e63eca32ce0ab2c5f3ed53e9"
        org.opencontainers.image.source: "https://github.com/linuxserver/docker-duplicati"
        org.opencontainers.image.title: "Duplicati"
        org.opencontainers.image.url: "https://github.com/linuxserver/docker-duplicati/packages"
        org.opencontainers.image.vendor: "linuxserver.io"
        org.opencontainers.image.version: "v2.0.6.3-2.0.6.3_beta_2021-06-17-ls167"
  
      logging:
        driver: "journald"
        options: {}
  
      mac_address: "02:42:ac:11:00:13"
  
      network_mode: "bridge"
  
      ports:
        - "8200:8200/tcp"
  
      privileged: yes
  
      restart: "always"
  
      security_opt:
        - "label=disable"
  
      volumes:
        - "duplicati-data:/config"
        - "/mnt/drivepool:/backups"
        - "/mnt:/source"
  
      working_dir: "/"