version: "3.7"

services:
  mealie-frontend:
    image: hkotel/mealie:latest
    container_name: mealie
    hostname: mealie

    environment:
    # Set Frontend ENV Variables Here
      - ALLOW_SIGNUP=true # disable after setting up your accounts!
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
    restart: unless-stopped
    ports:
      - "9925:80" # adjust to your liking 
    network_mode: "bridge"
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/mealie/data:/app/data/    