services:

    mealie:
  
      cap_drop:
        - "AUDIT_CONTROL"
        - "BLOCK_SUSPEND"
        - "DAC_READ_SEARCH"
        - "IPC_LOCK"
        - "IPC_OWNER"
        - "LEASE"
        - "LINUX_IMMUTABLE"
        - "MAC_ADMIN"
        - "MAC_OVERRIDE"
        - "NET_ADMIN"
        - "NET_BROADCAST"
        - "SYSLOG"
        - "SYS_ADMIN"
        - "SYS_BOOT"
        - "SYS_MODULE"
        - "SYS_NICE"
        - "SYS_PACCT"
        - "SYS_PTRACE"
        - "SYS_RAWIO"
        - "SYS_RESOURCE"
        - "SYS_TIME"
        - "SYS_TTY_CONFIG"
        - "WAKE_ALARM"
  
      container_name: "mealie"
  
      entrypoint:
        - "/bin/sh"
        - "-c"
        - "$MEALIE_HOME/mealie/run.sh"
  
      environment:
        - "PATH=/opt/poetry/bin:/opt/pysetup/.venv/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        - "LANG=C.UTF-8"
        - "GPG_KEY=E3FF2839C048B25C084DEBE9B26995E310250568"
        - "PYTHON_VERSION=3.9.10"
        - "PYTHON_PIP_VERSION=21.2.4"
        - "PYTHON_SETUPTOOLS_VERSION=58.1.0"
        - "PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/3cb8888cc2869620f57d5d2da64da38f516078c7/public/get-pip.py"
        - "PYTHON_GET_PIP_SHA256=c518250e91a70d7b20cceb15272209a4ded2a0c263ae5776f129e0d9b5674309"
        - "MEALIE_HOME=/app"
        - "PYTHONUNBUFFERED=1"
        - "PYTHONDONTWRITEBYTECODE=1"
        - "PIP_NO_CACHE_DIR=off"
        - "PIP_DISABLE_PIP_VERSION_CHECK=on"
        - "PIP_DEFAULT_TIMEOUT=100"
        - "POETRY_HOME=/opt/poetry"
        - "POETRY_VIRTUALENVS_IN_PROJECT=true"
        - "POETRY_NO_INTERACTION=1"
        - "PYSETUP_PATH=/opt/pysetup"
        - "VENV_PATH=/opt/pysetup/.venv"
        - "PRODUCTION=true"
        - "APP_PORT=80"
        - "PUID=1000"
        - "PGID=1000"
  
      hostname: "edd5d46cffbe"
  
      image: "docker.io/hkotel/mealie:latest"
  
      ipc: "private"
  
      logging:
        driver: "journald"
        options: {}
  
      mac_address: "02:42:ac:11:00:07"
  
      network_mode: "bridge"
  
      ports:
        - "9925:80/tcp"
  
      restart: "always"
  
      volumes:
        - "mealie_data:/app/data"
  
      working_dir: "/"