services:

  omada-controller:

    command:
      - "/usr/bin/java"
      - "-server"
      - "-Xms128m"
      - "-Xmx1024m"
      - "-XX:MaxHeapFreeRatio=60"
      - "-XX:MinHeapFreeRatio=30"
      - "-XX:+HeapDumpOnOutOfMemoryError"
      - "-XX:HeapDumpPath=/opt/tplink/EAPController/logs/java_heapdump.hprof"
      - "-Djava.awt.headless=true"
      - "-cp"
      - "/opt/tplink/EAPController/lib/*::/opt/tplink/EAPController/properties:"
      - "com.tplink.smb.omada.starter.OmadaLinuxMain"

    container_name: "omada-controller"

    entrypoint:
      - "/entrypoint.sh"

    environment:
      - "MANAGE_HTTP_PORT=8088"
      - "MANAGE_HTTPS_PORT=8043"
      - "PORTAL_HTTP_PORT=8088"
      - "PORTAL_HTTPS_PORT=8043"
      - "SHOW_MONGODB_LOGS=false"
      - "SHOW_SERVER_LOGS=true"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

    hostname: "omada-controller"

    image: "docker.io/mbentley/omada-controller:latest"

    ipc: "private"

    logging:
      driver: "journald"
      options: {}

    mac_address: "omada-contoller"

    network_mode: "bridge"

    ports:
      - "27001:27001/udp"
      - "29810:29810/udp"
      - "29811:29811/tcp"
      - "29812:29812/tcp"
      - "29813:29813/tcp"
      - "29814:29814/tcp"
      - "8043:8043/tcp"
      - "8088:8088/tcp"

    restart: "always"

    volumes:
      - "${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/omada/work:/opt/tplink/EAPController/work"
      - "${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/omada/data:/opt/tplink/EAPController/data"
      - "${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/omada/logs:/opt/tplink/EAPController/logs"

    working_dir: "/opt/tplink/EAPController/lib"