services:

    omada-controller:
  
      cap_drop:
        - "AUDIT_CONTROL"
        - "BLOCK_SUSPEND"
        - "DAC_READ_SEARCH"
        - "IPC_LOCK"
        - "IPC_OWNER"
        - "LEASE"
        - "LINUX_IMMUTABLE"
        - "MAC_ADMIN"
        - "MAC_OVERRIDE"
        - "NET_ADMIN"
        - "NET_BROADCAST"
        - "SYSLOG"
        - "SYS_ADMIN"
        - "SYS_BOOT"
        - "SYS_MODULE"
        - "SYS_NICE"
        - "SYS_PACCT"
        - "SYS_PTRACE"
        - "SYS_RAWIO"
        - "SYS_RESOURCE"
        - "SYS_TIME"
        - "SYS_TTY_CONFIG"
        - "WAKE_ALARM"
  
      command:
        - "/usr/bin/java"
        - "-server"
        - "-Xms128m"
        - "-Xmx1024m"
        - "-XX:MaxHeapFreeRatio=60"
        - "-XX:MinHeapFreeRatio=30"
        - "-XX:+HeapDumpOnOutOfMemoryError"
        - "-XX:HeapDumpPath=/opt/tplink/EAPController/logs/java_heapdump.hprof"
        - "-Djava.awt.headless=true"
        - "-cp"
        - "/opt/tplink/EAPController/lib/*::/opt/tplink/EAPController/properties:"
        - "com.tplink.smb.omada.starter.OmadaLinuxMain"
  
      container_name: "omada-controller"
  
      entrypoint:
        - "/entrypoint.sh"
  
      environment:
        - "MANAGE_HTTP_PORT=8088"
        - "MANAGE_HTTPS_PORT=8043"
        - "PORTAL_HTTP_PORT=8088"
        - "PORTAL_HTTPS_PORT=8043"
        - "SHOW_MONGODB_LOGS=false"
        - "SHOW_SERVER_LOGS=true"
        - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  
      hostname: "25d216dcca34"
  
      image: "docker.io/mbentley/omada-controller:latest"
  
      ipc: "private"
  
      labels:
        maintainer: "Matt Bentley <mbentley@mbentley.net>"
        org.opencontainers.image.source: "https://github.com/mbentley/docker-omada-controller"
  
      logging:
        driver: "journald"
        options: {}
  
      mac_address: "02:42:ac:11:00:03"
  
      network_mode: "bridge"
  
      ports:
        - "27001:27001/udp"
        - "29810:29810/udp"
        - "29811:29811/tcp"
        - "29812:29812/tcp"
        - "29813:29813/tcp"
        - "29814:29814/tcp"
        - "8043:8043/tcp"
        - "8088:8088/tcp"
  
      restart: "always"
  
      volumes:
        - "omada-data:/opt/tplink/EAPController/data"
        - "omada-logs:/opt/tplink/EAPController/logs"
        - "omada-work:/opt/tplink/EAPController/work"
  
      working_dir: "/opt/tplink/EAPController/lib"