services:

  overseer:

    container_name: "overseer"

    entrypoint:
      - "/init"

    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "PS1=$(whoami)@$(hostname):$(pwd)\\$ "
      - "HOME=/config"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_VERBOSITY=1"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "VIRTUAL_ENV=/lsiopy"
      - "LSIO_FIRST_PARTY=true"

    hostname: "overseer"

    image: "docker.io/linuxserver/overseerr:latest"

    logging:
      driver: "journald"
      options: {}

    network_mode: "bridge"

    ports:
      - "5000:5055/tcp"

    restart: "unless-stopped"

    volumes:
      - "${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/overseer/config:/config"

    working_dir: "/"