services:

  plex-meta-manager:

    container_name: "plex-meta-manager"

    entrypoint:
      - "/init-pmm"

    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "PS1=$(whoami)@$(hostname):$(pwd)\\$"
      - "PMM_RUN=false"
      - "PMM_OVERLAYS=true"
      - "PMM_TIME=05:00"
      - "TZ=America/New_York"
      - "PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "HOME=/config"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_VERBOSITY=1"
      - "S6_STAGE2_HOOK=/init-hook"
      - "VIRTUAL_ENV=/lsiopy"
      - "LSIO_FIRST_PARTY=true"
      - "PYTHONIOENCODING=utf-8"

    hostname: "plex-meta-manager"

    image: "docker.io/linuxserver/plex-meta-manager:latest"

    ipc: "private"

    logging:
      driver: "journald"
      options: {}

    network_mode: "bridge"

    restart: "unless-stopped"

    volumes:
      - "${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/plex-meta-manager/config:/config"

    working_dir: "/"