version: "2.1"

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/radarr/config:/config
      - /media/drivepool:/movies
      - /media/drivepool:/downloads # Should be the same as the download client's folder
    network_mode: "bridge"
    ports:
      - 7878:7878
    restart: unless-stopped