version: "2.1"

services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/sonarr/config:/config
      - /media/drivepool:/data/tv
      - /media/drivepool:/downloads # Should be the same as the download client's folder
    network_mode: "bridge"
    ports:
      - 8989:8989
    restart: unless-stopped