services:

    tdarr-node:
  
      container_name: "tdarr-node"
  
      devices:
        - "/dev/dri:/dev/dri"
  
      entrypoint:
        - "/init"
  
      environment:
        - "nodeID=PlexServer"
        - "serverIP=192.168.1.79"
        - "serverPort=8266"
        - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        - "HOME=/home/Tdarr"
        - "LANGUAGE=en_US.UTF-8"
        - "LANG=en_US.UTF-8"
        - "TERM=xterm"
        - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
        - "LIBVA_DRIVERS_PATH=/usr/lib/x86_64-linux-gnu/dri"
        - "LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu"
        - "NVIDIA_DRIVER_CAPABILITIES=compute,video,utility"
        - "NVIDIA_VISIBLE_DEVICES=all"
        - "HANDBRAKE=1.6.1"
        - "WEB_UI_PORT=8265"
        - "SERVER_PORT=8266"
        - "NODE_PORT=8267"
        - "PUID=1000"
        - "PGID=1000"
        - "UMASK=002"
        - "TZ=America/New_York"
  
      hostname: "d5342824eb5f"
  
      image: "ghcr.io/haveagitgat/tdarr_node:2.00.18.2"
  
      ipc: "private"
  
      logging:
        driver: "journald"
        options: {}
          
      network_mode: "bridge"
  
      ports:
        - "8267:8267/tcp"
  
      restart: "always"
  
      security_opt:
        - "label=disable"
  
      volumes:
        - "tdarr-config:/app/configs"
        - "tdarr-logs:/app/logs"
        - "/mnt/drivepool:/drivepool/media"
        - "/mnt/drivepool:/drivepool/transcode_cache"
  
      working_dir: "/"