services:

  tdarr:

    container_name: "tdarr"

    devices:
      - "/dev/dri:/dev/dri"

    entrypoint:
      - "/init"

    environment:
      - "HANDBRAKE=1.5.1"
      - "internalNode=true"
      - "nodeID=Server-Node"
      - "serverIP=0.0.0.0"
      - "serverPort=8266"
      - "webUIPort=8265"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "HOME=/home/Tdarr"
      - "LANGUAGE=en_US.UTF-8"
      - "LANG=en_US.UTF-8"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "LIBVA_DRIVERS_PATH=/usr/lib/x86_64-linux-gnu/dri"
      - "LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu"
      - "NVIDIA_DRIVER_CAPABILITIES=compute,video,utility"
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "WEB_UI_PORT=8265"
      - "SERVER_PORT=8266"
      - "NODE_PORT=8267"
      - "PUID=1000"
      - "PGID=1000"
      - "UMASK=002"
      - "TZ=America/New_York"

    hostname: "tdarr"

    image: "docker.io/haveagitgat/tdarr:2.00.18.2"

    ipc: "private"
    
    logging:
      driver: "journald"
      options: {}

    network_mode: "bridge"

    ports:
      - "8265:8265/tcp"
      - "8266:8266/tcp"

    restart: "unless-stopped"

    security_opt:
      - "label=disable"

    volumes:
      - "${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/tdarr/logs:/app/logs"
      - "${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/tdarr/server:/app/server"
      - "/media/drivepool:/drivepool/media"
      - "/media/drivepool:/drivepool/transcode_cache"
      - "${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/tdarr/configs:/app/configs"

    working_dir: "/"