services:

  tubesync:

    container_name: "tubesync"

    entrypoint:
      - "/init"

    environment:
      - "PGID=1000"
      - "PUID=1000"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "DEBIAN_FRONTEND=noninteractive"
      - "HOME=/root"
      - "LANGUAGE=en_US.UTF-8"
      - "LANG=en_US.UTF-8"
      - "LC_ALL=en_US.UTF-8"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "PYTHONPATH=/app:"

    hostname: "tubesync"

    image: "ghcr.io/meeb/tubesync:latest"

    ipc: "private"

    logging:
      driver: "journald"
      options: {}

    network_mode: "bridge"

    ports:
      - "4848:4848/tcp"

    restart: "unless-stopped"

    volumes:
      - "${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/tubesync/config:/config"
      - "/media/drivepool/Youtube:/downloads"

    working_dir: "/app"