services:

  uptime-kuma:

    command:
      - "node"
      - "server/server.js"

    container_name: "uptime-kuma"

    entrypoint:
      - "/usr/bin/dumb-init"
      - "--"
      - "extra/entrypoint.sh"

    environment:
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "NODE_VERSION=16.20.0"
      - "YARN_VERSION=1.22.19"

    hostname: "uptime-kuma"

    image: "docker.io/louislam/uptime-kuma:1"

    ipc: "private"

    logging:
      driver: "journald"
      options: {}

    network_mode: "bridge"

    ports:
      - "3001:3001/tcp"

    restart: "unless-stopped"

    volumes:
      - "${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/uptime-kuma/data:/app/data"

    working_dir: "/app"